// Generated by CoffeeScript 1.10.0
(function() {
  var App;

  App = (function() {
    function App() {
      var body, pane;
      pane = new CUI.SimplePane({
        padded: true,
        content: new CUI.Label({
          text: "Content"
        }),
        header_left: new CUI.Label({
          text: "Header left"
        }),
        header_right: CUI.Pane.getToggleFillScreenButton(),
        header_center: new CUI.Label({
          text: "Header center"
        }),
        footer_left: new CUI.Label({
          text: "Footer left"
        }),
        footer_right: new CUI.Label({
          text: "Footer right"
        }),
        force_header: true
      });
      body = new CUI.BorderLayout({
        west: {
          content: new CUI.Label({
            centered: true,
            text: "West"
          })
        },
        east: {
          content: new CUI.Label({
            centered: true,
            text: "East"
          })
        },
        center: {
          content: pane
        },
        north: {
          content: new CUI.Label({
            centered: true,
            text: "North"
          })
        },
        south: {
          content: new CUI.Label({
            centered: true,
            text: "South"
          })
        }
      });
      CUI.dom.append(document.body, body);
    }

    return App;

  })();

  CUI.ready(function() {
    return new App();
  });

}).call(this);
